# Generated by Django 6.0.2 on 2026-02-05 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('preconditions', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('expected', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('P0', 'P0 - Blocker'), ('P1', 'P1 - Critical'), ('P2', 'P2 - Major'), ('P3', 'P3 - Minor')], default='P2', max_length=4)),
                ('type', models.CharField(choices=[('functional', 'Functional'), ('api', 'API'), ('ui', 'UI')], default='functional', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testcases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_testcases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
