# Generated by Django 6.0.2 on 2026-02-05 07:22

import django.db.models.deletion
import testcases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=testcases.models.attachment_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='testcases.testcase')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
