# Generated by Django 6.0.2 on 2026-02-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_version'),
        ('testcases', '0002_testcaseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='projects.version'),
        ),
    ]
