# Generated by Django 6.0.2 on 2026-02-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcase_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_item',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
