# Generated by Django 6.0.2 on 2026-02-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_testcase_test_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
