# Generated by Django 6.0.2 on 2026-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_testcase_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], db_index=True, default='na', max_length=20),
        ),
    ]
