# Generated by Django 6.0.2 on 2026-02-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0008_testcase_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A'), ('pending', 'PEND')], db_index=True, default='pending', max_length=20),
        ),
    ]
