# Generated by Django 6.0.2 on 2026-02-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_testcase_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('functional', 'Functional'), ('performance', 'Performance'), ('compatibility', 'Compatibility'), ('usability', 'Usability'), ('api', 'API'), ('automation', 'Automation'), ('ui', 'UI')], default='functional', max_length=20),
        ),
    ]
